# Generated by Django 3.1.2 on 2021-01-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('1', 'Ambient'), ('2', 'Blues'), ('3', 'Bumpers & Stingers'), ('4', 'Chill Out'), ('5', 'Cinematic'), ('6', 'Classical'), ('7', 'Corporate'), ('8', 'Country'), ('9', 'Electronic'), ('10', 'Folk'), ('11', 'Hip Hop'), ('12', 'Holidays & Special Events'), ('13', 'Horror'), ('14', 'Jazz'), ('15', 'Kids & Family'), ('16', 'Pop'), ('17', 'Religious'), ('18', 'Rhythm & Blues'), ('19', 'Rock'), ('20', 'World')], max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(blank=True, null=True, upload_to='uploaded/%Y/%M/%D')),
            ],
        ),
    ]
