# Generated by Django 3.1.2 on 2021-01-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicLibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiclib',
            name='genre',
            field=models.CharField(choices=[('ambient', 'Ambient'), ('blues', 'Blues'), ('bumpers & stingers', 'Bumpers & Stingers'), ('chill out', 'Chill Out'), ('cinematic', 'Cinematic'), ('classical', 'Classical'), ('corporate', 'Corporate'), ('country', 'Country'), ('electronic', 'Electronic'), ('folk', 'Folk'), ('hip hop', 'Hip Hop'), ('holidays & special events', 'Holidays & Special Events'), ('horror', 'Horror'), ('jazz', 'Jazz'), ('kids and family', 'Kids & Family'), ('pop', 'Pop'), ('religious', 'Religious'), ('rhythm & blues', 'Rhythm & Blues'), ('rock', 'Rock'), ('world', 'World')], max_length=100),
        ),
    ]
