# Generated by Django 3.1.3 on 2021-02-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicLibrary', '0002_auto_20210127_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musiclib',
            name='upload',
        ),
        migrations.AddField(
            model_name='musiclib',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='music-lib/%Y/%M/%D'),
        ),
    ]
