# Generated by Django 3.1.3 on 2021-01-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buymodel',
            name='dataToken',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='buymodel',
            name='paid',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='buymodel',
            name='dod',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buymodel',
            name='exchange_key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
