# Generated by Django 3.1.3 on 2020-11-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserUploadedAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_uploaded_audio/%Y/%m/%d')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
