# Generated by Django 3.1.3 on 2020-12-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioVideoMerge', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserUploadedAudio',
        ),
    ]
